OPENAI_API_KEY="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"
SF_USER='ANANYAG'
SF_PASSWORD='Password1234!'
SF_ACCOUNT='OXJTHKI-UN86547'
SF_WAREHOUSE='COMPUTE_WH'
SF_DATABASE = 'analyticsdb'
SF_SCHEMA = 'PUBLIC'
SF_ROLE='ACCOUNTADMIN'
